// slug -> { 中文名, ISO alpha-2, 近似中心点 [lat, lon] }
window.COUNTRIES = {
  albania: { n: '阿尔巴尼亚', iso: 'AL', lat: 41.2, lon: 20.0 },
  argentina: { n: '阿根廷', iso: 'AR', lat: -38.4, lon: -63.6 },
  australia: { n: '澳大利亚', iso: 'AU', lat: -25.3, lon: 133.8 },
  austria: { n: '奥地利', iso: 'AT', lat: 47.5, lon: 14.6 },
  barbados: { n: '巴巴多斯', iso: 'BB', lat: 13.2, lon: -59.5 },
  belize: { n: '伯利兹', iso: 'BZ', lat: 17.2, lon: -88.5 },
  bermuda: { n: '百慕大', iso: 'BM', lat: 32.3, lon: -64.8 },
  bolivia: { n: '玻利维亚', iso: 'BO', lat: -16.3, lon: -63.6 },
  'bosnia-and-herzegovina': { n: '波黑', iso: 'BA', lat: 43.9, lon: 17.7 },
  brasil: { n: '巴西', iso: 'BR', lat: -14.2, lon: -51.9 },
  bulgaria: { n: '保加利亚', iso: 'BG', lat: 42.7, lon: 25.5 },
  'cabo-verde': { n: '佛得角', iso: 'CV', lat: 16.0, lon: -24.0 },
  canada: { n: '加拿大', iso: 'CA', lat: 56.1, lon: -106.3 },
  'caribbean-netherlands': { n: '加勒比荷兰', iso: 'BQ', lat: 12.2, lon: -68.2 },
  chile: { n: '智利', iso: 'CL', lat: -35.7, lon: -71.5 },
  china: { n: '中国', iso: 'CN', lat: 35.9, lon: 104.2 },
  'costa-rica': { n: '哥斯达黎加', iso: 'CR', lat: 9.7, lon: -83.8 },
  cyprus: { n: '塞浦路斯', iso: 'CY', lat: 35.1, lon: 33.4 },
  'czech-republic': { n: '捷克', iso: 'CZ', lat: 49.8, lon: 15.5 },
  'dominican-republic': { n: '多米尼加', iso: 'DO', lat: 18.7, lon: -70.2 },
  ecuador: { n: '厄瓜多尔', iso: 'EC', lat: -1.8, lon: -78.2 },
  'el-salvador': { n: '萨尔瓦多', iso: 'SV', lat: 13.8, lon: -88.9 },
  ellada: { n: '希腊', iso: 'GR', lat: 39.1, lon: 21.8 },
  espana: { n: '西班牙', iso: 'ES', lat: 40.5, lon: -3.7 },
  france: { n: '法国', iso: 'FR', lat: 46.6, lon: 2.2 },
  grenada: { n: '格林纳达', iso: 'GD', lat: 12.1, lon: -61.7 },
  guadeloupe: { n: '瓜德罗普', iso: 'GP', lat: 16.3, lon: -61.6 },
  honduras: { n: '洪都拉斯', iso: 'HN', lat: 15.2, lon: -86.2 },
  hrvatska: { n: '克罗地亚', iso: 'HR', lat: 45.1, lon: 15.2 },
  hungary: { n: '匈牙利', iso: 'HU', lat: 47.2, lon: 19.5 },
  iceland: { n: '冰岛', iso: 'IS', lat: 64.9, lon: -19.0 },
  ireland: { n: '爱尔兰', iso: 'IE', lat: 53.4, lon: -8.2 },
  israel: { n: '以色列', iso: 'IL', lat: 31.0, lon: 34.9 },
  italia: { n: '意大利', iso: 'IT', lat: 41.9, lon: 12.6 },
  jordan: { n: '约旦', iso: 'JO', lat: 30.6, lon: 36.2 },
  kenya: { n: '肯尼亚', iso: 'KE', lat: -0.0, lon: 37.9 },
  luxembourg: { n: '卢森堡', iso: 'LU', lat: 49.8, lon: 6.1 },
  maldives: { n: '马尔代夫', iso: 'MV', lat: 3.2, lon: 73.2 },
  malta: { n: '马耳他', iso: 'MT', lat: 35.9, lon: 14.4 },
  mauritius: { n: '毛里求斯', iso: 'MU', lat: -20.3, lon: 57.6 },
  mexico: { n: '墨西哥', iso: 'MX', lat: 23.6, lon: -102.6 },
  netherlands: { n: '荷兰', iso: 'NL', lat: 52.1, lon: 5.3 },
  norge: { n: '挪威', iso: 'NO', lat: 60.5, lon: 8.5 },
  panama: { n: '巴拿马', iso: 'PA', lat: 8.5, lon: -80.8 },
  peru: { n: '秘鲁', iso: 'PE', lat: -9.2, lon: -75.0 },
  philippines: { n: '菲律宾', iso: 'PH', lat: 12.9, lon: 121.8 },
  poland: { n: '波兰', iso: 'PL', lat: 51.9, lon: 19.1 },
  portugal: { n: '葡萄牙', iso: 'PT', lat: 39.4, lon: -8.2 },
  'puerto-rico': { n: '波多黎各', iso: 'PR', lat: 18.2, lon: -66.5 },
  'repubblica-di-san-marino': { n: '圣马力诺', iso: 'SM', lat: 43.9, lon: 12.5 },
  romania: { n: '罗马尼亚', iso: 'RO', lat: 45.9, lon: 25.0 },
  senegal: { n: '塞内加尔', iso: 'SN', lat: 14.5, lon: -14.5 },
  seychelles: { n: '塞舌尔', iso: 'SC', lat: -4.7, lon: 55.5 },
  'sint-maarten': { n: '圣马丁', iso: 'SX', lat: 18.0, lon: -63.1 },
  slovenija: { n: '斯洛文尼亚', iso: 'SI', lat: 46.2, lon: 14.8 },
  'south-africa': { n: '南非', iso: 'ZA', lat: -30.6, lon: 22.9 },
  'sri-lanka': { n: '斯里兰卡', iso: 'LK', lat: 7.9, lon: 80.8 },
  turkey: { n: '土耳其', iso: 'TR', lat: 39.0, lon: 35.2 },
  'united-kingdom': { n: '英国', iso: 'GB', lat: 54.0, lon: -2.0 },
  'united-states': { n: '美国', iso: 'US', lat: 39.8, lon: -98.6 },
  'us-virgin-islands': { n: '美属维尔京群岛', iso: 'VI', lat: 18.3, lon: -64.9 },
  vietnam: { n: '越南', iso: 'VN', lat: 16.0, lon: 107.8 },
  zambia: { n: '赞比亚', iso: 'ZM', lat: -13.1, lon: 27.8 },
  zanzibar: { n: '桑给巴尔', iso: 'TZ', lat: -6.1, lon: 39.2 },
};

window.flagEmoji = function (iso) {
  if (!iso) return '🌐';
  return iso
    .toUpperCase()
    .replace(/./g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));
};
